 version: 2
 # -------------------------
 #      DEFAULTS VALUES
 # -------------------------
 defaults: &defaults
   working_directory: ~/currencyExchange
   docker:
     - image: circleci/node:12.9.1-browsers
 # -------------------------
 #          JOBS
 # -------------------------
 jobs:
   build:
     <<: *defaults
     steps:
       - checkout
       - run: echo "start fetch"
       - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
       - run: yarn install
       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
   test:
     <<: *defaults
     steps:
       - run: yarn test