 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:12.9.1-browsers
     working_directory: ~/currencyExchange
     steps:
       - checkout
       - run: echo "start"
       - run: yarn install
       - run: yarn test