version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:12.9.1-browsers
     steps:
       - checkout
       - run: echo "A first hello"
   build:
     docker:
       - image: circleci/node:12.9.1-browsers
     steps:
       - checkout
       - run: echo "A first hello"