 version: 2
 jobs:
   build:
     docker:
       - image: circleci/node:12.9.1-browsers
     steps:
       - checkout
       - run: echo "start"
       - restore_cache:
         key: v1-dependencies-{{ checksum "package.json" }}
       - run: yarn install